[package]
name = "notepad"
version = "0.1.0"
authors = ["5225225 <5225225@mailbox.org>"]
edition = "2018"

[dependencies]
wasmlib = {path = "../wasmlib"}
serde = { version = "1.0", default-features = false, features = ["derive"] }
